name: pnpsci2
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.11
  - cudatoolkit=11.0
  - torchvision
  - torchaudio
  - matplotlib
  - pytorch
  - jupyterlab
  - h5py
  - tifffile
  - tensorboardX
  - scikit-image
  - scipy
  - pip:
    - opencv-python
    - colour-science
    - colour_demosaicing

